AniWebApp/Controllers/AppController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AniWebApp.Controllers
{
    public class AppsController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

    }
}

AniWebApp/Views/Shared/_CommonLayout.cshtml
@using MvcFlash.Core.Extensions
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section heading {
    @RenderSection("heading", false)
}

@section scripts
{
    @RenderSection("scripts", false)
}

<div>

    <ol class="breadcrumb" role="navigation">
        <li><a href="@Url.Action("Index", "Home")">Home</a></li>
        @RenderSection("breadcrumbs", false)
        <li class="active">@(String.IsNullOrWhiteSpace(ViewBag.BreadcrumbTitle) ? ViewBag.Title : ViewBag.BreadcrumbTitle)</li>
    </ol>

    <h1>
        @ViewBag.Title
        @if (!string.IsNullOrWhiteSpace(ViewBag.TitleSmall))
        {
            <small>@ViewBag.TitleSmall</small>
        }
    </h1>

    <div class="row">
        <div class="col-md-10 col-sm-9">
            @if (!string.IsNullOrWhiteSpace(ViewBag.Lead))
            {
                <p class="lead">
                    @Html.Raw(ViewBag.Lead)
                </p>
            }
        </div>
        <div class="col-md-2 col-sm-3 text-right">
            @RenderSection("header_side_content", false)
        </div>
    </div>

</div>

@Html.Flash()

@RenderBody()

AniWebApp/Views/Shared/_Layout.cshtml
@using AniWebApp.Helpers
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - MattEland.com</title>

    @* JQuery Includes *@
    <link rel="stylesheet" href="http://ajax.aspnetcdn.com/ajax/jquery.ui/1.11.4/themes/dot-luv/jquery-ui.css">
    <script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.1.3.min.js"></script>
    <script src="http://ajax.aspnetcdn.com/ajax/jquery.ui/1.11.4/jquery-ui.min.js"></script>
    
    @* Enable JQuery date pickers *@
    <script type="text/javascript">
        $(function () {
            $(".datefield").datepicker();
        });
    </script>

    @* Site includes *@
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/modernizr")

    @Scripts.Render("~/scripts/bootstrap-386.min.js")
    @Styles.Render(Html.GetThemeCss())
    @Styles.Render("~/Content/Site.min.css")

    <meta name="description" content="Personal Development and Research Projects by Matt Eland" />

    @RenderSection("heading", false)
</head>
<body>
    <header>
        <div class="navbar navbar-inverse navbar-static-top" role="banner">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        MENU
                    </button>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li class='@Html.IsActive("Home", "Index")'>@Html.ActionLink("Home", "Index", "Home")</li>

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Projects <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li>@Html.ActionLink("All Projects", "Index", "Projects")</li>
                                <li>@Html.ActionLink("ANI Project", "ANI", "Projects")</li>
                                <li>@Html.ActionLink("Pi-MFD", "PiMFD", "Projects")</li>
                                <li>@Html.ActionLink("Mobile Apps", "Index", "Apps")</li>
                            </ul>
                        </li>

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">ANI <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li>@Html.ActionLink("Project Home", "ANI", "Projects")</li>
                                <li>@Html.ActionLink("Weather", "Index", "Weather")</li>
                                <li>@Html.ActionLink("Frost", "Frost", "Weather")</li>
                                <li>@Html.ActionLink("Traffic", "Index", "Traffic")</li>
                                <li>@Html.ActionLink("Ratings", "Index", "Ratings")</li>
                            </ul>
                        </li>

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Apps <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li>@Html.ActionLink("All Apps", "Index", "Apps")</li>
                                <li>@Html.ActionLink("Seeking God", "SeekingGod", "Apps")</li>
                                <li>@Html.ActionLink("Seeking Jesus", "SeekingJesus", "Apps")</li>
                                <li>@Html.ActionLink("Life Lights", "LifeLights", "Apps")</li>
                            </ul>
                        </li>

                        <li>@Html.ActionLink("About", "About", "Home")</li>


                    </ul>
                    @if (Request.IsAuthenticated)
            {
                        <ul class="nav navbar-nav navbar-right">
                            <li>
                                @Html.ActionLink("My Profile", "MyProfile", "Account")
                            </li>
                            <li>
                                <a href="javascript:document.getElementById('logoutForm').submit()">
                                    Log out
                                    @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new {id = "logoutForm"}))
                            {
                                        @Html.AntiForgeryToken()
                            }
                                </a>
                            </li>

                        </ul>
            }
            else
            {
                        <ul class="nav navbar-nav navbar-right">
                            <li>@Html.ActionLink("Register", "Register", "Account", routeValues: null, htmlAttributes: new {id = "registerLink"})</li>
                            <li>@Html.ActionLink("Log in", "Login", "Account", routeValues: null, htmlAttributes: new {id = "loginLink"})</li>
                        </ul>
            }
                </div>
            </div>
        </div>
    </header>
<div class="container body-content">
    @RenderBody()
</div>
<footer>
    <div class="container">
        <hr />
        <p>&copy; @DateTime.Now.Year Matt Eland</p>
    </div>
</footer>

<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

@RenderSection("scripts", required: false)

</body>
</html>

AniWebApp/Views/Shared/_ListLayout.cshtml
@using AniWebApp.Helpers
@{
    Layout = "~/Views/Shared/_CommonLayout.cshtml";
    ViewBag.TableClasses = "table-responsive table-hover";
}

@section heading {
    @RenderSection("heading", false)
}

@section scripts
{
    @RenderSection("scripts", false)

    @*@Scripts.Render("https://cdnjs.cloudflare.com/ajax/libs/jquery-bootgrid/1.1.4/jquery.bootgrid.min.js")*@
}

@section header_side_content
{
    @RenderSection("header_side_content", false)
}

@section breadcrumbs
{
    @RenderSection("breadcrumbs", false)
}

@RenderSection("top_content", false)

<div class="panel panel-default @StyleHelper.GetHiddenClass(ViewBag.HasListItems)">

    @if (!string.IsNullOrWhiteSpace(ViewBag.ListTitle))
    {
        <div class="panel-heading">
            @ViewBag.ListTitle
        </div>
    }

    <div class="panel-body">
        <table class="table @ViewBag.TableClasses"
               data-toggle="bootgrid"
               data-sorting="false"
               data-navigation="1"
               data-rowCount="25"
               data-columnSelection="false" >
            <thead>
                <tr>
                    @RenderSection("table_headers", true)
                </tr>
            </thead>
            <tbody>
                @RenderSection("table_body", true)
            </tbody>
        </table>

    </div>
</div>

<p class="alert @ViewBag.NoListItemsClass @StyleHelper.GetHiddenClass(!ViewBag.HasListItems)">
    @ViewBag.NoListItemsMessage
</p>

@RenderBody()